### ISSUE TITLE
How to trust your distrubted binaries? How does this work?

### ISSUE THREAD

**Issue by tngreene** [portapps/portapps#1]
Hi,

This looks like an awesome software package, but, how can I trust the binaries and support files for Skype.exe, Slack.exe, etc? Where do you source them from? (And out of curiosity, do you have the rights to do so?)

Also, how does this work, in general? What mechanisms do you use to fake having registry keys installed and such?

**Comment by crazy-max** [comment]
Hi @tngreene,

I'll try to answer your questions fairly accurately. And I think following that I will create a FAQ section to add my answers.

> This looks like an awesome software package, but, how can I trust the binaries and support files for Skype.exe, Slack.exe, etc? Where do you source them from?

In a word, you can completely trust my binaries compared to those delivered by other systems offering portable applications. Why ? Because all the process is open source as well as the building process and the portapp executable. Let's take Skype as an example.

The "main" file of each portapps repositories is the [`build.properties`](https://github.com/portapps/skype-portable/blob/master/build.properties) file. It's a spec file for the building procedure of a portapp using [Apache Ant](https://ant.apache.org/).

In this file you have the [original source of the distributed package from the official website](https://github.com/portapps/skype-portable/blob/master/build.properties#L34).
For Skype this file is at the folllowing url : `https://endpoint920510.azureedge.net/s4l/s4l/download/win/Skype-8.25.0.5.exe`.

If you go on the official website of Skype the official link is `https://go.skype.com/windows.desktop.download`, but it redirects to an azure CDN `https://endpoint920510.azureedge.net/s4l/s4l/download/win/Skype-8.25.0.5.exe` (same as the one in the build properties) :

```
https://go.skype.com/windows.desktop.download

HTTP/1.1 301 Moved Permanently
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Location: https://get.skype.com/go/getskype-skypeforwindows
Strict-Transport-Security: max-age=31536000; includeSubDomains
Date: Tue, 24 Jul 2018 14:16:17 GMT
Content-Length: 0

https://get.skype.com/go/getskype-skypeforwindows

HTTP/1.1 302 Found
Cache-Control: no-store, must-revalidate, no-cache, max-age=0, private
Pragma: no-cache
Content-Length: 0
Content-Type: text/html; charset=utf-8
Location: https://endpoint920510.azureedge.net/s4l/s4l/download/win/Skype-8.25.0.5.exe
Vary: User-Agent
Server: Microsoft-HTTPAPI/2.0
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Date: Tue, 24 Jul 2018 14:16:18 GMT

https://endpoint920510.azureedge.net/s4l/s4l/download/win/Skype-8.25.0.5.exe
```

And concerning the building process to make it "portapp", you can read [logs on Appveyor](https://ci.appveyor.com/project/portapps/skype-portable/build/18?fullLog=true). Everything is revealed here. To resume, the building steps are :
* Install Golang, Java and ANT
* Load required libraries
  * ant-contrib
  * 7zip
  * dep (dependency manager for golang)
  * [rcedit](https://github.com/electron/rcedit/) (to add icons to the final executable)
  * innoextract (to extract the original setup)
  * innosetup (to package the final portapp as a portable setup using innosetup)
  * upx (to compress the portapp executable)
* Download the original setup from the official website
* Extract this setup
* Download go dependencies using dep (based on Gopkg.toml)
* "Go" generate (prepare versioning file for the final executable and rcedit resources)
* "Go" build (create the portapp executable)
* Compressing executable with UPX
* Load asar (tool to extract app.asar in Skype because Skype is based on Electron)
* [Replace paths in app.asar](https://github.com/portapps/skype-portable/blob/master/build.properties#L23-L28)
* Repackaging app.asar
* Create 7z portapp archive
* Create innosetup portapp setup
* Send artefacts from Appveyor to Github releases
* Done :)

Concerning your question about the mechanism, the magic appears in the app.asar refactoring for Skype ;) This process is quite the same for the current portapps available [but can differ following the original setup (can be archive, electron app, nsis, innosetup, multi arch, etc...)](https://github.com/portapps/portapps/tree/master/.build).

**Comment by tngreene** [comment]
Very informative! Thank you!
