### ISSUE TITLE
[AntiVirus] Continued Trojan Flagging of PortApps

### ISSUE THREAD

**Issue by Hammerfest** [portapps/portapps#29]
For lack of a better central issue reporting area, I am posting this here.

As reported before with Windows Defender by another person here, PortApps continue to be flagged as a Trojan (the other person reported only Skype Portable).

Since into last year both Windows Defender and BitDefender have continually flagged the 4 Portable Apps from PortApps.io that I use as a Trojan through use of heuristic detection.

I have attempted to notify both several times and submitted what they asked for, however, 8 months now and they continue to be a royal pain in the ass!

Skype/Discord/Boarderless/Slack

I have reported this for other software, but typically until the application author makes a report, BitDefender wont do squat, this is my request to ping them upside the head with a rather large spiked club...

**Comment by crazy-max** [comment]
Hello @Hammerfest, thanks for your report.

> As reported before with Windows Defender by another person here, PortApps continue to be flagged as a Trojan (the other person reported only Skype Portable).

I have indeed detected myself in the last few days new detections on the wrapper since Portapps uses the latest version of Golang (1.12).

> Since into last year both Windows Defender and BitDefender have continually flagged the 4 Portable Apps from PortApps.io that I use as a Trojan through use of heuristic detection.

I send the false positives payloads of the wrapper to the antivirus vendors as soon as possible (often BitDefender which includes the definitions of a dozen other vendors, Microsoft Defender recently with gnupg-portable and also McAfee). Yesterday for example, I have sent the [latest wrapper of Firefox portable](https://www.virustotal.com/#/file/8655a993db81755f506324da69c52d2fc8bcdb0d381dd8c47e4d6adcf045c160/detection) to BitDefender, Microsoft and McAfee and we should have an answer tomorrow.

Microsoft Defender recently flagged gnupg-portable wrapper and I received their analysis detection with _no malware detected_:

![image](https://user-images.githubusercontent.com/1951866/57290617-129eb980-70be-11e9-8612-7ce6bdf506a3.png)

> I have attempted to notify both several times and submitted what they asked for, however, 8 months now and they continue to be a royal pain in the ass!

I find it really surprising that the program is still suspected on your side. For example, the wrapper for Skype in its latest version no longer raises heuristic alerts for the most popular editors: https://www.virustotal.com/#/file/18d9d26cd81df645943ccd1b238e5d0cf2376b9484d046b05118031d3c3ff70d/detection

> Skype/Discord/Boarderless/Slack

Can you give me a link to a VirusTotal analysis please ?

Thanks
