### ISSUE TITLE
portapps Windows Defender bug

### ISSUE THREAD

**Issue by marius-joe** [portapps/portapps#46]
Unfortunately the portapps installer for WhatsApp under Windows 10 gave me the following warning and stopped running :/

The appended screenshot is in German, the warning means:
„Your computer was protected by Windows.
Windows Defender SmartScreen prohibited the start of an unknown app. The execution of this app may be a risk for the PC.“

I‘ve managed to run WhatsApp now through the 7z archive, so I think something has to be adjusted in the installer to be run on the current Windows 10 version.

Greetings
Marius

![4565D1C3-EFAA-41E0-BD23-6969BB0001AC](https://user-images.githubusercontent.com/43403160/61154892-b148fb80-a4ef-11e9-80c4-c8b2b92e1da1.png)

**Comment by crazy-max** [comment]
Hi @marius-joe,

As [discussed](https://github.com/crazy-max/WindowsSpyBlocker/issues/145#issuecomment-475331098) for another Windows app I maintained, the application should be signed by a certificate to no longer have this SmartScreen alert. Since the cost of a software certificate is expensive, it will stay as it is for now. What you can do is [whitelisting](https://www.addictivetips.com/windows-tips/whitelist-apps-in-the-smartscreen-on-windows-10/) the executable in the program properties.
