### ISSUE TITLE
WebStorm

### ISSUE THREAD

**Issue by asharpefr** [portapps/portapps#83]
> Please follow this guide to file a proper request report : https://portapps.io/doc/request-app/

* Name : WebStorm
* Description : JavaScript IDE
* Website : https://www.jetbrains.com/webstorm/
* License (e.g. Freeware, OSS, GPL, MIT, etc) : Commercial
* Comment (anything else which might help) :

**Comment by niemtin007** [comment]
Hi crazy-max,

Could you do me a favor to make a portable for the WebStorm? Because some extensions for WebStorm do not work well in the IntelliJ. I think it has a similar structure to the IntelliJ IDEA, so it will not take up too much of your time.

Your portable apps run fast and clean. Thank you for your contribution.

Thanks,
